#!/bin/bash
# Endymion-AI Quick Reference Cheat Sheet
# Updated: January 2026

echo "=========================================="
echo "🐄 Endymion-AI Demo Cheat Sheet"
echo "=========================================="
echo ""

echo "📋 Prerequisites:"
echo "  1. cd /home/xuxoramos/endymion-ai"
echo "  2. source .venv/bin/activate"
echo "  3. Start Docker: cd docker && sudo docker-compose up -d"
echo ""

echo "🚀 Run Demos:"
echo "  # Complete end-to-end demo (Bronze → Silver → Gold)"
echo "  ./demo/run_demo_all.sh"
echo ""
echo "  # Interactive demo (10 steps)"
echo "  ./demo/run_demo.sh"
echo ""
echo "  # Simple quick demo"
echo "  ./demo/run_demo_simple.sh"
echo ""

echo "🎨 Timeline Visualization:"
echo "  # Simple timeline"
echo "  python demo/timeline_simple.py"
echo ""
echo "  # Full timeline (all cows)"
echo "  python demo/timeline.py"
echo ""
echo "  # Specific cow"
echo "  python demo/timeline.py <cow-id>"
echo ""

echo "🔄 Sync Services:"
echo "  # Manual operational sync (SQL projection)"
echo "  ./demo/sync-projection.sh"
echo ""
echo "  # Manual analytics sync (Bronze/Silver/Gold)"
echo "  ./demo/sync-analytics.sh"
echo ""
echo "  # Start continuous syncs (background)"
echo "  # Operational: ./demo/sync-projection.sh --loop 5 &"
echo "  # Analytics:   SYNC_INTERVAL=30 ./demo/sync-analytics.sh &"
echo ""

echo "📊 Monitoring & Health:"
echo "  # Health check"
echo "  curl http://localhost:8000/health | jq"
echo ""
echo "  # Metrics"
echo "  curl http://localhost:8000/metrics"
echo ""
echo "  # Generate monitoring dashboard"
echo "  python -m backend.monitoring.dashboard dashboard.html"
echo "  xdg-open dashboard.html"
echo ""

echo "🔍 Manual Queries:"
echo "  # SQL Server - Events (Event Store)"
echo "  sudo docker exec -i cattlesaas-sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -d cattlesaas -Q \"SELECT COUNT(*) FROM operational.cow_events;\""
echo ""
echo "  # SQL Server - Projection (CQRS Read Model)"
echo "  sudo docker exec -i cattlesaas-sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -d cattlesaas -Q \"SELECT * FROM operational.cows;\""
echo ""
echo "  # Bronze Layer (Delta Lake)"
echo "  python databricks/bronze/query_bronze.py"
echo ""
echo "  # Silver Layer (check setup)"
echo "  python databricks/silver/setup_silver.py"
echo ""

echo "🐄 API Examples:"
echo "  TENANT_ID='550e8400-e29b-41d4-a716-446655440000'"
echo ""
echo "  # List cows"
echo "  curl http://localhost:8000/api/v1/cows -H \"X-Tenant-ID: \$TENANT_ID\" | jq"
echo ""
echo "  # Create cow"
echo "  curl -X POST http://localhost:8000/api/v1/cows \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H \"X-Tenant-ID: \$TENANT_ID\" \\"
echo "    -d '{\"tag_number\": \"DEMO-999\", \"name\": \"TestCow\", \"breed\": \"Angus\", \"sex\": \"female\", \"birth_date\": \"2024-01-01\", \"weight_kg\": 400}' | jq"
echo ""
echo "  # Update cow weight"
echo "  curl -X PUT http://localhost:8000/api/v1/cows/<cow-id> \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H \"X-Tenant-ID: \$TENANT_ID\" \\"
echo "    -d '{\"weight_kg\": 450}' | jq"
echo ""
echo "  # Analytics - Herd composition"
echo "  curl http://localhost:8000/api/v1/analytics/herd-composition -H \"X-Tenant-ID: \$TENANT_ID\" | jq"
echo ""

echo "🏗️ Lakehouse Layers:"
echo "  # Bronze - Setup & Ingest"
echo "  python databricks/bronze/setup_bronze.py"
echo "  python databricks/bronze/ingest_from_sql.py --once"
echo ""
echo "  # Silver - State Resolution (SCD Type 2)"
echo "  python databricks/silver/setup_silver.py"
echo "  python databricks/silver/resolve_cow_state.py"
echo ""
echo "  # Gold - Analytics"
echo "  python databricks/gold/gold_daily_snapshots.py"
echo "  python databricks/gold/gold_herd_composition.py"
echo "  python databricks/gold/rebuild_all.py"
echo ""

echo "🌐 Frontend (React + Vite):"
echo "  cd frontend"
echo "  npm install           # First time only"
echo "  npm run dev           # Starts on http://localhost:3000"
echo ""

echo "🧹 Cleanup:"
echo "  # Stop processes"
echo "  pkill -f uvicorn"
echo "  pkill -f vite"
echo "  pkill -f sync"
echo ""
echo "  # Clear SQL data"
echo "  sudo docker exec -i cattlesaas-sqlserver /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -C -d cattlesaas -Q \"TRUNCATE TABLE operational.cow_events;\""
echo ""
echo "  # Stop Docker"
echo "  cd docker && sudo docker-compose down -v"
echo ""

echo "🔧 Troubleshooting:"
echo "  # Check Docker containers"
echo "  sudo docker ps"
echo ""
echo "  # Check FastAPI"
echo "  curl http://localhost:8000/health"
echo "  tail -f /tmp/fastapi.log"
echo ""
echo "  # Check Frontend"
echo "  curl http://localhost:3000"
echo "  tail -f /tmp/frontend.log"
echo ""
echo "  # Check sync logs"
echo "  tail -f /tmp/sync-projection.log"
echo "  tail -f /tmp/sync-analytics.log"
echo ""
echo "  # Verify Bronze layer"
echo "  python databricks/bronze/check_bronze.py"
echo ""

echo "📚 Documentation:"
echo "  README.md                    - Main project overview"
echo "  demo/README.md               - Demo guide"
echo "  UPDATES.md                   - Bug fixes & improvements"
echo "  ARCHITECTURE.md              - Architecture deep dive"
echo "  databricks/README.md         - Lakehouse overview"
echo "  backend/jobs/SYNC_JOB_DOCUMENTATION.md - Sync details"
echo "  backend/monitoring/MONITORING.md - Monitoring system"
echo ""

echo "🎯 Quick Start:"
echo "  1. ./setup.sh                     # Initial setup"
echo "  2. ./demo/run_demo_all.sh         # Run complete demo"
echo "  3. Open http://localhost:3000     # View web UI"
echo ""

echo "=========================================="
